Added routing for login and ensured that login works for fake databas…
johndpjr/AgTern pull request #135
Opened 2023-05-20 05:32 UTC by Jwdegames

…e on SwaggerUI. We might need some actualy users to test it with the user model

2023-07-09 21:20 UTC, JeremyEastham requested changes
Great work so far!

2023-07-09 21:20 UTC, JeremyEastham commented on backend/app/api/endpoints/login.py
> +from ..deps import get_db
```suggestion
from backend.api import get_db
```
This should be an absolute import. Relative imports may cause errors due to the module initialization order. Prefer absolute imports when possible.

2023-07-09 21:20 UTC, JeremyEastham commented on requirements.txt
> +nltk
```suggestion
```
`nltk` is listed on the previous line.

2023-07-09 21:20 UTC, JeremyEastham commented on requirements.txt
> +python-multipart
```suggestion
```
`python-multipart` is listed on the previous line.

2023-07-09 21:20 UTC, JeremyEastham commented on backend/app/api/endpoints/login.py
> +}
```suggestion
```
Delete this if possible to avoid confusion.

2023-07-09 21:20 UTC, JeremyEastham commented on backend/app/api/endpoints/login.py
> +    return {"status": "success"}
These functions should be deleted. Modify models in `user.py` instead.

2023-07-09 21:20 UTC, JeremyEastham commented on backend/app/crud/crud.py
> +        # Maybe call db.refresh()?
Please test if this is needed.

2023-07-09 21:20 UTC, JeremyEastham commented on frontend/src/_generated/api/services/JobsService.ts
> +    ): CancelablePromise<Array<Job>> {
Please make sure the formatting in this file is consistent with the other services. I believe `openapi-typescript-codegen` does not indent parameters.

2023-08-14 00:00 UTC, Jwdegames commented on backend/app/crud/crud.py
> +        # Maybe call db.refresh()?
I was just doing what create_jobs() was doing, so this is why that's there.

2023-08-14 00:02 UTC, Jwdegames commented on frontend/src/_generated/api/services/JobsService.ts
> +    ): CancelablePromise<Array<Job>> {
That's how it is in LoginService.ts.

2023-08-15 09:33 UTC, johndpjr approved these changes
Looks great- good job Jacob. Tested and logged in successfully!

2023-08-15 09:34 UTC, merged