implement apply button
johndpjr/AgTern pull request #17
Opened 2022-09-25 19:48 UTC by judz5

Apply button now opens webpage of link from `_var_internship_link` _(if valid)_

2022-09-25 23:39 UTC, johndpjr requested changes
In addition to a few formatting things, I know I didn't add this on the TODO, but please modify the docstring of this function to describe what the function does (what is the "Response" of the callback?)

2022-09-25 23:39 UTC, johndpjr commented on agtern/gui/frames/internship_detail_frame.py
> +        if(link): # Ensure not empty
```suggestion
        if link:  # Ensure not empty
```
Complying with PEP8 standards: at least 2 spaces for inline comments and no parentheses in `if` statement

2022-09-25 23:39 UTC, johndpjr commented on agtern/gui/frames/internship_detail_frame.py
> +
```suggestion
```
Extra line

2022-09-26 11:51 UTC, judz5 commented
👍🏻 let me know if you want more detail in docstring, hopefully formatting is okay now.

2022-09-26 12:09 UTC, johndpjr commented
Other than the formatting suggestions, looks good!

2022-09-26 12:49 UTC, judz5 commented
which formatting suggestions? was there more other than the spacing and parentheses you said?

2022-09-26 13:42 UTC, judz5 commented
oops, my bad i thought i had no parentheses and you wanted them lol ill fix that

2022-09-26 14:03 UTC, johndpjr commented
One more change - there's an "s" after `self,`. Check my suggested change

2022-09-26 16:08 UTC, judz5 commented
ok hopefully thats it, sorry for all the little mistakes

2022-09-26 16:29 UTC, johndpjr approved these changes
Looks good!

2022-09-26 16:59 UTC, merged