Made each logger commit to their own file. This makes it easier to ch…
johndpjr/AgTern pull request #178
Opened 2023-11-05 15:14 UTC by Jwdegames

…eck which each program was doing. Also, allow logger to be run in parallel.

Note: For in the future, when we decide to spawn child threads/ processes, we need to consider whether to make new loggers for them as well.

2023-11-05 20:47 UTC, JeremyEastham requested changes
Let's discuss the implications of removing the rotating file handler before merging. Thanks!

2023-11-05 20:47 UTC, JeremyEastham commented on backend/app/utils/logger.py
> +    # rotate_handler = logging.handlers.TimedRotatingFileHandler(
Is there any particular reason you decided to remove the rotating file handler? If the server is running for a long time, these files could grow quite large. We likely don't care about old logs that take up the majority of this space.

2023-11-05 21:00 UTC, Jwdegames commented on backend/app/utils/logger.py
> +    # rotate_handler = logging.handlers.TimedRotatingFileHandler(
Yeah, I wasn't sure if we should prune the logs after midnight. But it shouldn't be too hard to replace back the RotatingFileHandler. We would just give each process a different log file.

2023-11-05 21:18 UTC, JeremyEastham commented on backend/app/utils/logger.py
> +    # rotate_handler = logging.handlers.TimedRotatingFileHandler(
For now, I think we should use the rotating file handler in addition to a modified naming scheme.

2023-11-05 21:29 UTC, JeremyEastham commented on backend/app/utils/logger.py
> +        time.strftime("(%Y-%m-%d)-(%H-%M-%S)"), getpid()
Using the PID in the filename will work for multiprocessing, but it may not work for multiple threads in the same process. This will probably need to be tested before pushing.

2023-11-08 18:48 UTC, JeremyEastham commented
This section of the Python documentation contains a couple of sample logging synchronization implementations:
https://docs.python.org/3/howto/logging-cookbook.html#logging-to-a-single-file-from-multiple-processes

2023-11-12 05:38 UTC, Jwdegames commented on backend/app/utils/logger.py
> +        time.strftime("(%Y-%m-%d)-(%H-%M-%S)"), getpid()
According to the documentation, the logger is thread safe - "The logging module is intended to be thread-safe without any special work needing to be done by its clients". So it looks like we only need to worry about multiprocessing.

2024-03-13 23:05 UTC, johndpjr approved these changes

2024-03-13 23:05 UTC, merged