Features/169/implement oauth on backend
johndpjr/AgTern pull request #201
Opened 2023-11-27 02:56 UTC by Jwdegames

2023-11-27 04:15 UTC, johndpjr requested changes

2023-11-28 00:22 UTC, Jwdegames commented on backend/app/models/user.py
I was thinking in case in the future we wanted to have more login services in the future. If we added any other services, then we need to check the id of each service, or we could just check made_password..

2023-11-28 00:24 UTC, Jwdegames commented on debugdump.txt
Must have accidentally autogenerated this. Will remove.

2023-11-28 00:26 UTC, Jwdegames commented on requirements.txt
Yes, version 2.108.0

2023-11-28 00:26 UTC, Jwdegames commented on requirements.txt
Will add

2023-11-28 00:26 UTC, Jwdegames commented on backend/app/api/endpoints/login.py
Will remove.

2023-11-28 00:26 UTC, Jwdegames commented on frontend/src/_generated/api/services/LoginService.ts
Will remove.

2023-11-28 00:26 UTC, Jwdegames commented on frontend/src/app/shared/components/google-sign-in/google-sign-in.component.ts
Will remove.

2023-11-28 00:32 UTC, Jwdegames commented on backend/app/api/endpoints/login.py
> +CLIENT_ID = "710734565405-3nkf5plf0m4p460osals94rnksheoh93.apps.googleusercontent.com"
Will do.

2023-11-28 00:44 UTC, johndpjr commented
By the dotenv I meant use the files instead of system environment variables. I'd take a look at `settings.py` and the `envs` folder.

![image](https://github.com/johndpjr/AgTern/assets/78290887/9798daf1-8f69-45ab-b502-8cd1393c5580)

2023-11-28 14:27 UTC, johndpjr approved these changes
Good job Jacob! Looks good

2023-11-28 14:28 UTC, merged