Move to client-server architecture
johndpjr/AgTern pull request #57
Opened 2022-10-29 16:15 UTC by johndpjr

This is in a **draft** state, but this will move the structure of a project from one that was only client-side (GUI app and scraping done on client) to a client-server architecture (GUI app that communicates to a server via an API, where the data is stored and the scraping is done).

2022-10-31 18:56 UTC, JeremyEastham commented
A fair amount of this code is part of the new scraping system that I thought I merged already. I don't know what happened, but that's probably why `main` won't run right now.

2022-10-31 19:32 UTC, JeremyEastham requested changes
Great work so far! Take a look at the changes I suggested. We can discuss them if you have any questions.

Also, remember to add imports if you end up accepting some of my suggestions that contain things you hadn't imported (such as `ValidationError`).

2022-10-31 19:32 UTC, JeremyEastham commented on agtern/__main__.py
> +    parser.add_argument("--save-internships", action="store_true")
Consider inverting this argument. I was wondering why internships weren't saving and this was the reason. Saving should probably be opt-out instead of opt-in.

2022-10-31 19:32 UTC, JeremyEastham commented on agtern/common/api.py
> +            return Internship(**data)
Since `Internship` is a Pydantic Model, it may raise `ValidationErrors`. Currently, if there is a validation error, the whole program crashes. Consider something like this:
```suggestion
            try:
                return Internship(**data)
            except ValidationError as errors:
                LOG.error("Unable to create internship!")
                LOG.error(errors)
```

2022-10-31 19:32 UTC, JeremyEastham commented on agtern/common/api.py
> +        return None
Since this file is client-side only, it should not live in `common`. `common` should contain modules common to the client and the server, such as logging, data management, and models used by both the client and the server.

2022-10-31 19:32 UTC, JeremyEastham commented on agtern/common/api.py
> +        return None
We need to ensure everything is separated so that we don't accidentally deploy server-side code to the client.

2022-10-31 19:32 UTC, JeremyEastham commented on agtern/common/schemas.py
> +        orm_mode = True
Are these models used on both the client and the server? If not, please refactor them into the correct module(s).

2022-10-31 19:32 UTC, JeremyEastham commented on agtern/common/api.py
> +        resp = self.session.post(self.base_url + "/internships/",
Also, see my comment in `server.py` regarding this route.

2022-10-31 19:32 UTC, JeremyEastham commented on agtern/server/server.py
> +async def create_internship(internship: schemas.InternshipCreate, db: Session = Depends(get_db)):
Should this route exist? We don't want clients to be able to make entries in our database. Such a request could be maliciously crafted to pollute our data.

The API should only contain routes that the client needs to display data. Internship creation should all be server-side.

2022-10-31 19:32 UTC, JeremyEastham commented on agtern/common/models.py
> +        validate_assignment = True
```suggestion
    class Config:
        validate_assignment = True

    @validator("period", pre=True)
    def validate_period(cls, value):
        if isinstance(value, str):
            return value.capitalize()
        else:
            return value
```
This validator makes `period` case insensitive. Previously, validation would fail for something like `"SUMMER"`.

2022-10-31 19:32 UTC, JeremyEastham commented on agtern/server/database/crud.py
> +    db_internship = models.Internship(**internship.dict())
```suggestion
    try:
        db_internship = models.Internship(**internship.dict())
    except ValidationError as errors:
        LOG.error("Could not create internship!")
        LOG.error(errors)
        return None
```
If `Internship` validation fails, it doesn't say why. You need to catch the validation errors and log them. You could either deal with the `None` return value when you use this function, or you could catch the validation errors where you use this function instead.

2022-10-31 23:22 UTC, johndpjr commented on agtern/__main__.py
> +    parser.add_argument("--save-internships", action="store_true")
I feel that defaulting to saving will inevitably create duplicates in the database (we would need to only insert unique ones). This could be solved later

2022-10-31 23:24 UTC, johndpjr commented on agtern/common/api.py
> +        resp = self.session.get(self.base_url + "/internships/")
Should `self.base_url` just include the `/api` at the end? I know we said that this server could actually serve the website files, but that seems like a far time from now

2022-10-31 23:26 UTC, johndpjr commented on agtern/common/schemas.py
> +        orm_mode = True
Good catch- they are used by `server` and `api`; will change this

2022-10-31 23:30 UTC, JeremyEastham commented on agtern/common/api.py
> +        resp = self.session.get(self.base_url + "/internships/")
Once the Angular frontend is in place, this code will be irrelevant. It is more important that the backend remains consistent. You're right, it probably makes more sense to add `/api` to `base_url`.

2022-10-31 23:31 UTC, johndpjr commented on agtern/server/server.py
> +async def create_internship(internship: schemas.InternshipCreate, db: Session = Depends(get_db)):
I agree- it shouldn't exist on the public API. Maybe a feature down the road is we can allow people to upload custom internships (that haven't been scraped - but we would need to rate-limit and give authentication). I tried to only do creation server-side but got some circular dependency issues; will look into it again

2022-10-31 23:32 UTC, JeremyEastham commented on agtern/__main__.py
> +    parser.add_argument("--save-internships", action="store_true")
Okay, leave it for now. Consider logging a warning if internships won't be saved to alleviate confusion.

2022-11-01 01:47 UTC, JeremyEastham commented on agtern/server/server.py
> +async def create_internship(internship: schemas.InternshipCreate, db: Session = Depends(get_db)):
If you want to commit it as-is, I can look into that. I was planning on looking into authentication (which would solve these issues). What I was planning before the API existed is for the scraper to write directly to the database while the server reads from it. You may run into concurrency issues if both are using the same connection on different threads (unless SQLAlchemy is thread-safe, which it may be).

2022-11-02 16:36 UTC, johndpjr commented on agtern/common/schemas.py
> +        orm_mode = True
The client actually uses the `Internship` in `schemas.py`, so we'll leave this

2022-11-02 16:54 UTC, johndpjr commented on agtern/common/api.py
> +        return None
Leaving this for a future issue, as we'll work with authentication. `api` is used by server to create internships (not ideal).

2022-11-03 02:47 UTC, JeremyEastham approved these changes
LGTM!

2022-11-03 02:51 UTC, merged